baseURL = "https://ctpsstaff.github.io/boston-region-stops/"
languageCode = "en-us"
title = "Boston Region STOPS Model"
theme = "ananke"

[params]
  description = "Official documentation and resource hub for the Boston Region STOPS model, prepared for the Boston Region MPO."
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Documentation"
  url = "/docs/"
  weight = 20

[[menu.main]]
  name = "Announcements"
  url = "/announcements/"
  weight = 30
  
[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 40